package com.lekasp.spring_boot.spring_boot_mvc_security_bootstrap.security;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}